package Program;

import java.io.File;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;

import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class Mahasiswa extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    String date1,date2,possibleaction,file_path,filename1;
    String attachment;
    MimeBodyPart messageBodyPart = new MimeBodyPart();
    Multipart multipart = new MimeMultipart();
    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa() {
        initComponents();
       show_data();
    }
public Mahasiswa(String user) {
        show_data();
        initComponents();
        jLabel1.setText(user);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bodypanel = new javax.swing.JPanel();
        log = new javax.swing.JPanel();
        lbnama = new javax.swing.JLabel();
        btn_approval = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_approval1 = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        Approval = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nam = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        kls = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        anggotapkn = new javax.swing.JTable();
        Edit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jur = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Email = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        subject = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        attach_name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Pengumuman = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bodypanel.setBackground(new java.awt.Color(0, 0, 0));

        log.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        log.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbnama.setText("nama");
        log.add(lbnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        btn_approval.setText("Curiculum Vitae");
        btn_approval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_approvalActionPerformed(evt);
            }
        });
        log.add(btn_approval, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, -1));

        jButton5.setText("Portofolio");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        log.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, -1));

        btn_logout.setText("LOG OUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        log.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, -1));

        jButton7.setText("Pengumuman");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        log.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, -1));

        jLabel6.setText("NAMA :");
        log.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-100.png"))); // NOI18N
        log.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homedosen.jpg"))); // NOI18N
        log.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        btn_approval1.setText("Curiculum Vitae");
        btn_approval1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_approval1ActionPerformed(evt);
            }
        });
        log.add(btn_approval1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, -1));

        menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu.setLayout(new java.awt.CardLayout());

        Approval.setBackground(new java.awt.Color(0, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("REGISTRASI ANGGOTA PKN");

        jLabel3.setText("Nama :");

        jLabel7.setText("NIM :");

        jLabel8.setText("Jurusan :");

        jLabel9.setText("Kelas :");

        anggotapkn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        anggotapkn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anggotapknMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(anggotapkn);

        Edit.setText("Update");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatika", "Industri", "Mesin", "Sipil", "Elektronika", " " }));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informasi"));

        jLabel10.setText("Anda akan mengimputkan data anggota kelompok PKN");

        jLabel14.setText("dengan ketentuan Nama,NIM,Jurusan dan kelas.");

        jLabel15.setText("Maksimal 4 orang dalam kelompok PKN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton6.setText("Refresh Table");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ApprovalLayout = new javax.swing.GroupLayout(Approval);
        Approval.setLayout(ApprovalLayout);
        ApprovalLayout.setHorizontalGroup(
            ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApprovalLayout.createSequentialGroup()
                .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ApprovalLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ApprovalLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(ApprovalLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ApprovalLayout.createSequentialGroup()
                                .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ApprovalLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ApprovalLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(106, 106, 106)
                                .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(34, 34, 34))
                            .addGroup(ApprovalLayout.createSequentialGroup()
                                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(4, 4, 4)))
                        .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kls)
                            .addComponent(jur, 0, 165, Short.MAX_VALUE))))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        ApprovalLayout.setVerticalGroup(
            ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApprovalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ApprovalLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton6))
                    .addGroup(ApprovalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(Edit)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        menu.add(Approval, "card3");

        Email.setBackground(new java.awt.Color(0, 204, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("From :");

        jLabel11.setText("Subject :");

        jLabel12.setText("To :");

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        attach_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attach_nameActionPerformed(evt);
            }
        });

        text.setColumns(20);
        text.setRows(5);
        jScrollPane2.setViewportView(text);

        jButton4.setText("File");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("PORTOFOLIO");

        javax.swing.GroupLayout EmailLayout = new javax.swing.GroupLayout(Email);
        Email.setLayout(EmailLayout);
        EmailLayout.setHorizontalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailLayout.createSequentialGroup()
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 70, Short.MAX_VALUE))
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(13, 13, 13)))
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(to, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subject)
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addComponent(path, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(attach_name, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(from))
                .addGap(58, 58, 58)
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(534, 534, 534))
            .addGroup(EmailLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmailLayout.setVerticalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel13)
                .addGap(47, 47, 47)
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton4)))
                .addGap(22, 22, 22)
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attach_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        menu.add(Email, "card4");

        Pengumuman.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nilai");

        javax.swing.GroupLayout PengumumanLayout = new javax.swing.GroupLayout(Pengumuman);
        Pengumuman.setLayout(PengumumanLayout);
        PengumumanLayout.setHorizontalGroup(
            PengumumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengumumanLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel16)
                .addContainerGap(1043, Short.MAX_VALUE))
        );
        PengumumanLayout.setVerticalGroup(
            PengumumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengumumanLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel16)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        menu.add(Pengumuman, "card4");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void btn_approvalActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        //remove
        menu.removeAll();
        menu.repaint();
        menu.revalidate();
        //add
        menu.add(Approval);
        menu.repaint();
        menu.revalidate();
    }                                            

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        int exit = JOptionPane.YES_NO_OPTION;
        int dialog = JOptionPane.showConfirmDialog(this,"Anda yakin Log Out?",">_<",exit);
       if(dialog==0){
           Login lg = new Login();
            lg.setVisible(true);
           setVisible(false);
                   
       }else{
           
       }
    }                                          

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         String Nama = nam.getText();
          String Nim = nim.getText();
          String kelas = kls.getText();
          String jurusan = (String) jur.getSelectedItem();
          
          
try{
Statement statement = (Statement) Koneksi.GetConnection().createStatement();
statement.executeUpdate("insert into anggota VALUES ('" + Nama +"','"+ Nim +"','" + kelas +"','"+ jurusan +"');");
statement.close ();
JOptionPane.showMessageDialog(null, "data berhasil disimpan");
       

}catch (Exception t){
JOptionPane.showMessageDialog(null, "data gagal disimpan");
}     // TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String Nama = nam.getText();
          String Nim = nim.getText();
          String kelas = kls.getText();
          String jurusan = (String) jur.getSelectedItem();
          
          
          
try{
Statement statement = (Statement) Koneksi.GetConnection().createStatement();
statement.executeUpdate("DELETE FROM anggota WHERE nama='"+Nama+"'");
statement.close ();
JOptionPane.showMessageDialog(null, "data berhasil dihapus");
       

}catch (Exception t){
JOptionPane.showMessageDialog(null, "data gagal ");
        
}
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        final String user ="streetmeliodas69@gmail.com";
        final String pass ="rapier123";
        Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");             /*Mengautentikasi email Gmail yang digunakan untuk mengirim menggunakan protokol SMTP dengan port 587 */

		Session session = Session.getInstance(props,
		  new javax.mail.Authenticator() {
	          protected PasswordAuthentication getPasswordAuthentication() {
	          return new PasswordAuthentication(user, pass); /* Mengautentikasi password dan username email Gmail yang digunakan untuk mengirim email */
			}
		  });

		try {

			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress(from.getText()));
                        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to.getText()));
                        message.setSubject(subject.getText());
                        messageBodyPart.setText(text.getText());
                        multipart.addBodyPart(messageBodyPart);              /* Isi dari email yang dikirimkan */

                         if(path.getText().equals("") && attach_name.getText().equals("")){
                message.setContent(multipart);
                Transport.send(message);
                JOptionPane.showMessageDialog(null, "Send Succsess");
                
            }else {
                messageBodyPart= new MimeBodyPart();
                javax.activation.DataSource source = new FileDataSource(filename1);
                messageBodyPart.setDataHandler(new DataHandler(source));
                messageBodyPart.setFileName(attach_name.getText());
                multipart.addBodyPart(messageBodyPart);
                message.setContent(multipart);
                Transport.send(message);
                JOptionPane.showMessageDialog(null, "Send Succsess");
                         }   
            }catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
                    }
	
       
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename1 = f.getAbsolutePath();
        String namafile = f.getName();
        attach_name.setText(namafile);
        path.setText(filename1);
                
        
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         menu.removeAll();
        menu.repaint();
        menu.revalidate();
        //add
        menu.add(Email);
        menu.repaint();
        menu.revalidate();
    }                                        

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       try{
           String Nama = nam.getText();
          String Nim = nim.getText();
          String kelas = kls.getText();
          String jurusan = (String) jur.getSelectedItem();
          
          Statement statement = (Statement) Koneksi.GetConnection().createStatement();
statement.executeUpdate("UPDATE anggota SET nim='"+Nim+"',jurusan='"+jurusan+"',kelas='"+kelas+"'where nama='"+Nama+"'");
statement.close ();
          /*
          String sql1 ="UPDATE anggota SET nama='"+Nama+"',nim='"+Nim+"',jurusan='"+jurusan+"',kelas='"+kelas+"'where 1 ";
          ps =con.prepareStatement(sql1);
          ps.execute();
          */
          JOptionPane.showMessageDialog(null, "data berhasil di Update"); 
           
       }catch(Exception e){
           
       }
    }                                    

    private void anggotapknMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        int tbl = anggotapkn.getSelectedRow();
        
        nam.setText(anggotapkn.getValueAt(tbl, 1).toString());
        nim.setText(anggotapkn.getValueAt(tbl, 2).toString());
        jur.setSelectedItem(anggotapkn.getValueAt(tbl, 3).toString());
        kls.setText(anggotapkn.getValueAt(tbl, 4).toString());
        
    }                                       

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        DefaultTableModel tbll =(DefaultTableModel)anggotapkn.getModel();
        tbll.setRowCount(0);
        show_data();
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btn_approval1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void attach_nameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Approval;
    private javax.swing.JButton Edit;
    private javax.swing.JPanel Email;
    private javax.swing.JPanel Pengumuman;
    private javax.swing.JTable anggotapkn;
    private javax.swing.JTextField attach_name;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton btn_approval;
    private javax.swing.JButton btn_approval1;
    private javax.swing.JButton btn_logout;
    private javax.swing.JTextField from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jur;
    private javax.swing.JTextField kls;
    private javax.swing.JLabel lbnama;
    private javax.swing.JPanel log;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField path;
    private javax.swing.JTextField subject;
    private javax.swing.JTextArea text;
    private javax.swing.JTextField to;
    // End of variables declaration                   

    private void show_data() {
         DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NO.");
    model.addColumn("Nama");
    model.addColumn("NIM");
    model.addColumn("Kelas");
    model.addColumn("Jurusan");
    
    
    try{
        int no =1;
        String sql ="Select * From anggota limit 4";
        con = Koneksi.GetConnection();
        ps =con.prepareStatement(sql);
        rs=ps.executeQuery();
        
        while(rs.next()){
            model.addRow(new Object []{no++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
            
            anggotapkn.setModel(model);
        
        }
    }catch(SQLException e){
        System.out.println("error:"+e.getMessage());
    }
    }
}
